application: calcium-vector-91212
module: default
version: test
runtime: go
api_version: go1
automatic_scaling:
  max_concurrent_requests: 30

handlers:
- url: /.*
  script: _go_app
  secure: always

